FROM node:14.15.5

RUN mkdir -p /src/optimizador-kpis

WORKDIR /src/optimizador-kpis

COPY . .

RUN npm install --no-package-lock

RUN npm run build

EXPOSE 3000

ENV NUXT_HOST=0.0.0.0

ENV NUXT_PORT=3000

CMD npm run start